import com.sun.org.apache.xml.internal.utils.StringBufferPool;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {

        return "Hello world.";
    }

    public static Hoge init(){
      Hoge h = new Hoge();
      Row r1 = new Row();
      r1.cells.add(1);
      r1.cells.add(1);
      r1.cells.add(0);
      h.rows.add(r1);
      Row r2 = new Row();
      r2.cells.add(1);
      r2.cells.add(0);
      r2.cells.add(0);
      h.rows.add(r2);
      Row r3 = new Row();
      r3.cells.add(0);
      r3.cells.add(0);
      r3.cells.add(0);
      h.rows.add(r3);
      return h;
    }

    static String show(Hoge hoge){
      StringBuilder sb = new StringBuilder();
      for (int i = 0; i <hoge.rows.size() ; i++) {
        Row row = hoge.rows.get(i);
        for (int j = 0; j < row.cells.size(); j++) {
          Integer n = row.cells.get(j);
          if(n == 0){
            sb.append("□");
          }
          if(n == 1){
            sb.append("■");
          }

        }
        sb.append("\n");
      }
      return sb.toString();
    }

    static Hoge next(Hoge hoge){
      return hoge;
    }

    public static void main(String[] args) {
      try {
        Hoge hoge = init();
        while(true){
          System.out.println(show(hoge));
          Thread.sleep(1000);
          hoge = next(hoge);
        }
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
    }
}
